### ISSUE TITLE
Question about running cellSNP on merged BAM files from multiple samples

### ISSUE THREAD

**Issue by lmweber** [single-cell-genetics/cellSNP#10]
Hi, I have been running into some difficulties with running cellSNP/Vireo, and thought here would be a good place to ask. This is a follow-up to the questions Stephanie Hicks asked via Twitter a few weeks ago.

As discussed on Twitter, we are considering a multiplexed design for some future 10x scRNA-seq samples, and in anticipation of this, we are trying to do some evaluations on our existing (non-multiplexed) samples, to see how well Vireo would have performed at demultiplexing these if they were multiplexed.

The way we are trying to do this is: (i) combine BAM files from 3 separate scRNA-seq samples (i.e. simply merge them using `samtools merge`), (ii) run cellSNP to genotype cells, using either mode 1 (using known variants provided from the 1000 Genomes Project), or mode 3 (using our separate matched bulk RNA-seq samples), and then (iii) run Vireo.

However I have been getting stuck when trying to run cellSNP. I think it is either due to the way I have merged the BAM files, or due to the list of cell barcodes I am providing to cellSNP.

Do you have any advice about how you would go about doing this? E.g. maybe simply merging the BAM files is too simple (I have had a look in https://github.com/single-cell-genetics/vireo/tree/master/simulate, and see that you also used `samtools merge` there, but there is also quite a lot else going on in that script). For the list of cell barcodes, I have tried providing both the entire Cell Ranger barcode whitelist, or a parsed list of barcodes from the Cell Ranger output, but both are giving me errors -- I can't quite figure out from the documentation what I need to provide here; sorry if I missed something. (cellSNP also gives me a message saying it is actually running in mode 2, so maybe I am also providing the inputs incorrectly).

Any advice you could provide would be greatly appreciated. Or if you have a full worked example showing how to run a cellSNP analysis, this would also be very helpful -- I had a look but could only find Vireo examples beginning from the cellSNP output; sorry again if I missed something.

**Comment by huangyh09** [comment]
Hi Lukas,

Thanks for follow up the discussion here. It is indeed nice to test the synthetic mixture before the real experiments. 

First, I think `samtoools merge` can't resolve the issue that cell barcodes are overlapped between multiple samples, so the merged cell barcode may refer to multiple cells in different donors. That's the main motivation that we wrote the [python simulate](https://github.com/single-cell-genetics/vireo/tree/master/simulate), which we mainly manipulated the cell barcode by adding the donor id (as the lane id), so it will be barcode-1, barcode-2, etc. If you already keep the donor id in the lane id, then I guess `samtools` should be fine.

For the our python simulator, it requires cell barcodes to avoide parsing all whitelist, as most are empty drops. The input barcodes files should be each barcodes for each bam. For example if you pooling 4 samples, it will be `-b path/barocde_file1.tsv,path/barcode_file2.tsv,path/barocde_file3.tsv,path/barcode_file4.tsv` in the same order of bam files. BTW, the barcode file need to be plain text but not gzipped (sorry developped with cellrange v2).

Once you pool the bam files properly, you run cellSNP with giving a list of SNPs and cell barcodes, it should run in mode 1.

Let me know anything unclear.

Yuanhua

**Comment by lmweber** [comment]
Hi Yuanhua, thanks a lot for the reply, and for providing the `synth_pool.py` script. This makes sense -- so the way I was trying to merge the BAM files was too simple.

I have now tried running `synth_pool.py` together with the Cell Ranger BAM files and (gunzipped) filtered barcode lists per sample, to merge the BAM files, but now I am getting the following error:

```
Traceback (most recent call last):
  File "../synth_pool/synth_pool.py", line 266, in <module>
    main()
  File "../synth_pool/synth_pool.py", line 220, in main
    load_sample=False)
  File "/users/lweber/.local/lib/python3.7/site-packages/cellSNP/utils/vcf_utils.py", line 70, in load_VCF
    if vcf_file[-3:] == ".gz" or vcf_file[-4:] == ".bgz":
TypeError: 'NoneType' object is not subscriptable
```

If I understand this correctly, it is because I did not provide a VCF file to the `--regionFile` argument. However, if I provide a VCF file, then the script will return a BAM file containing only reads covering the given variants -- but I am trying to merge the BAM files and keep all reads.

Is there a way to run the script to merge BAM files without the `--regionFile` argument? (Sorry I am not so proficient at Python, otherwise I could probably just edit the script.)

**Comment by huangyh09** [comment]
Hi Lukas, you understanding is correct. This code indeed requries `--regionFile`, as it parses reads by covering a list of SNPs (see the [code](https://github.com/single-cell-genetics/vireo/blob/master/simulate/synth_pool.py#L119)). You could change this section of codes to cover the whole chromosome(s). However, this stragegy is probably not fast, and difficult to handle many settings.

Alternatively, you have the initial cell barcodes with the sample id when running cellranger (not sure if `--sample` or `--lanes` can do this?), then you can use `samtools merge`, which might be more efficient to pool the whole bam files.

Yuanhua

**Comment by lmweber** [comment]
Ok, thank you! I will try to merge the BAM files correctly, and then get back to you again if I have any further questions.
