### ISSUE TITLE
Change the flag filtering default to include PCR duplicates

### ISSUE THREAD

**Issue by GWW** [single-cell-genetics/cellSNP#13]
From my cursory understanding of cellSNP you filter all of the reads that are marked as PCR duplicates by Cell Ranger. However, this would remove a large number of UMI duplicates as noted by the [vartrix](https://github.com/10XGenomics/vartrix) documentation: 

`ignore alignments marked as duplicates? Take care when turning this on with scRNA-seq data, as duplicates are marked in that pipeline for every extra read sharing the same UMI/CB pair, which will result in most variant data being lost.`

I wouldn't be surprised if this negatively affects the performance of vireo on some datasets.

**Comment by hxj5** [comment]
Hi, thanks for your feedback. If the reads sharing the same UMI/CB pair are marked as PCR duplicates by CellRanger, cellSNP would filter them given a small value of parameter maxFLAG. As we found some test datasets on which CellRanger did not perform the marking, we would run CellRanger on a few more datasets, especially using its default parameters.

**Comment by GWW** [comment]
Alright, if you think it's the more reasonable choice to filter them.  Perhaps it may be worth explicitly stating in the manual that they are filtered by default and may lead to an increased SNV false negative rate, which has been the case in my experience.

**Comment by hxj5** [comment]
We have changed the default value of maxFLAG to include PCR duplicates for scRNA-seq data when UMItag is turned on and state it in the README file. Thanks for your advice!

**Comment by GWW** [comment]
No problem.  I am glad you made the change in our experience Vireo has performed extremely well using all of the reads including PCR duplicates.
